/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptimizationFrame.java
 *
 * Created on 2010-11-01, 13:24:20
 */
package piotrrr.thesis.gui;

import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import org.apache.log4j.PropertyConfigurator;
import piotrrr.thesis.bots.tuning.DuelEvalResults;
import piotrrr.thesis.bots.tuning.OptResults;
import piotrrr.thesis.bots.tuning.OptimizationRunner;
import piotrrr.thesis.common.CommFun;
import piotrrr.thesis.common.stats.StatsChartsFactory;
import piotrrr.thesis.tools.Dbg;

/**
 *
 * @author piotrrr
 */
public class OptimizationFrame extends javax.swing.JFrame {

    private static OptimizationFrame optFrameInstance;
    private OptResults optResults;

    /** Creates new form OptimizationFrame */
    public OptimizationFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        timescalejTextField1 = new javax.swing.JTextField();
        iterationsjTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        runjButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        maxIterScorejTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        evalRepetitionsjTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        fitnessjPanel5 = new javax.swing.JPanel();
        refreshResultsChartsjButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsjList1 = new javax.swing.JList();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        textjPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultDetailsTextArea1 = new javax.swing.JTextArea();
        killsChartjPanel5 = new javax.swing.JPanel();
        killsPerDeathjPanel6 = new javax.swing.JPanel();
        killsByBotTypejPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bots Optimization");
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Timescale");

        timescalejTextField1.setText("120");
        timescalejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timescalejTextField1ActionPerformed(evt);
            }
        });

        iterationsjTextField2.setText("100");

        jLabel2.setText("Iterations");

        runjButton1.setText("Run");
        runjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runjButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Iter time in seconds");

        maxIterScorejTextField1.setText("3600");

        jButton4.setText("Unblock current optimization");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        evalRepetitionsjTextField1.setText("20");

        jLabel4.setText("Evaluation repetitions");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maxIterScorejTextField1)
                            .addComponent(iterationsjTextField2)
                            .addComponent(timescalejTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(evalRepetitionsjTextField1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(runjButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timescalejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iterationsjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maxIterScorejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(evalRepetitionsjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runjButton1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Run Optimization", jPanel1);

        jButton2.setText("Save results");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Load results");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        fitnessjPanel5.setLayout(new java.awt.GridLayout(1, 1));
        jTabbedPane3.addTab("Fitness", fitnessjPanel5);

        refreshResultsChartsjButton4.setText("Refresh charts");
        refreshResultsChartsjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshResultsChartsjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshResultsChartsjButton4)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(refreshResultsChartsjButton4))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Results", jPanel3);

        resultsjList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resultsjList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(resultsjList1);

        resultDetailsTextArea1.setColumns(20);
        resultDetailsTextArea1.setRows(5);
        jScrollPane2.setViewportView(resultDetailsTextArea1);

        javax.swing.GroupLayout textjPanel4Layout = new javax.swing.GroupLayout(textjPanel4);
        textjPanel4.setLayout(textjPanel4Layout);
        textjPanel4Layout.setHorizontalGroup(
            textjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textjPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );
        textjPanel4Layout.setVerticalGroup(
            textjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textjPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Text", textjPanel4);

        killsChartjPanel5.setLayout(new java.awt.GridLayout(1, 0));
        jTabbedPane2.addTab("Kills", killsChartjPanel5);

        killsPerDeathjPanel6.setLayout(new java.awt.GridLayout(1, 1));
        jTabbedPane2.addTab("Kills per death", killsPerDeathjPanel6);

        killsByBotTypejPanel5.setLayout(new java.awt.GridLayout(1, 1));
        jTabbedPane2.addTab("Kills by bot type", killsByBotTypejPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Simulation Results", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runjButton1ActionPerformed
        int timescale = Integer.parseInt(timescalejTextField1.getText());
        int iterations = Integer.parseInt(iterationsjTextField2.getText());
        int iterScore = Integer.parseInt(maxIterScorejTextField1.getText());
        int reps = Integer.parseInt(evalRepetitionsjTextField1.getText());
        String mapName = "map2";
        OptimizationRunner.getInstance().runOptimization(timescale, iterations, iterScore, mapName, reps);
        optResults = new OptResults();
    }//GEN-LAST:event_runjButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OptimizationRunner.getInstance().stopOptimization();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        OptimizationRunner.getInstance().stopOptimization();
    }//GEN-LAST:event_formWindowClosing

    private void resultsjList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resultsjList1ValueChanged
        int si = resultsjList1.getSelectedIndex();
        if (si < 0 || si >= resultsjList1.getModel().getSize()) {
            return;
        }
        DuelEvalResults r = optResults.iterResults.get(si);
        displayResults(r);
    }//GEN-LAST:event_resultsjList1ValueChanged

    private void timescalejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timescalejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timescalejTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (optResults == null) {
                return;
            }
            JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
            fc.setApproveButtonText("Save");
            fc.setDialogTitle("Save current results");
            fc.showOpenDialog(this);
            System.out.println("Saving results to file: " + fc.getSelectedFile());
            CommFun.saveToFile(fc.getSelectedFile().getPath(), optResults);
            MyPopUpDialog.showMyDialogBox("Success", "Results saved successfully", MyPopUpDialog.info);
        } catch (Exception ex) {
            MyPopUpDialog.showMyDialogBox("Failed saving", "Failed saving the results!\n" + ex.toString(), MyPopUpDialog.error);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
            fc.setApproveButtonText("Open");
            fc.setDialogTitle("Open results");
            fc.showOpenDialog(this);
            System.out.println("Reading results from file: " + fc.getSelectedFile());
            OptResults res = (OptResults) CommFun.readFromFile(fc.getSelectedFile().getPath());
            optResults = res;
            refreshIterResults();
            MyPopUpDialog.showMyDialogBox("Success", "Results loaded successfully", MyPopUpDialog.info);
        } catch (Exception ex) {
            MyPopUpDialog.showMyDialogBox("Failed reading", "Failed reading the results!\n" + ex.toString(), MyPopUpDialog.error);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void refreshResultsChartsjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshResultsChartsjButton4ActionPerformed
        fitnessjPanel5.removeAll();
        LinkedList<double[]> evalScore = new LinkedList<double[]>();
        LinkedList<double[]> bestScores = new LinkedList<double[]>();
        int iter = 0;
        int bestScore = Integer.MIN_VALUE;
        for (DuelEvalResults res : optResults.iterResults) {
            if (res.score > bestScore) bestScore = res.score;
            evalScore.add(new double[] {iter, res.score});
            bestScores.add(new double[] {iter, bestScore});
            iter++;
        }
        LinkedList<String> series = new LinkedList<String>();
        series.add("Best fitness");
        series.add("Eval fitness");
        HashMap<String, LinkedList<double[]>> map = new HashMap<String, LinkedList<double[]>>();
        map.put(series.getFirst(), bestScores);
        map.put(series.getLast(), evalScore);
        fitnessjPanel5.add(StatsChartsFactory.getXYChart(series, map, "Fitness in evaluations", "Iteration", "Fitness"));

        fitnessjPanel5.revalidate();

    }//GEN-LAST:event_refreshResultsChartsjButton4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        OptimizationRunner.getInstance().unblockProcess();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void displayResults(DuelEvalResults r) {
        resultDetailsTextArea1.setText(r.toString());

        killsChartjPanel5.removeAll();
        killsChartjPanel5.add(StatsChartsFactory.getKillsInTimeByBot(r.stats));
        killsChartjPanel5.revalidate();
        
        killsPerDeathjPanel6.removeAll();
        killsPerDeathjPanel6.add(StatsChartsFactory.getKillsPerEachDeathByBot(r.stats));
        killsPerDeathjPanel6.revalidate();

        killsByBotTypejPanel5.removeAll();
        killsByBotTypejPanel5.add(StatsChartsFactory.getKillsInTimeByBotType(r.stats));
        killsByBotTypejPanel5.revalidate();

    }

    public void addResults(DuelEvalResults res) {
        Dbg.prn("adding results to list");
        optResults.iterResults.add(res);
        refreshIterResults();
    }

    public void refreshIterResults() {
        DefaultListModel m = new DefaultListModel();
        int i = 0;
        for (DuelEvalResults r : optResults.iterResults) {
            m.add(i, r.toShortString());
            i++;
        }
        resultsjList1.setModel(m);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        PropertyConfigurator.configure("log4j.properties");
        AppConfig.readConfig();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            } catch (Exception ex1) {
                System.err.println("No look and feel available :(");
                ex1.printStackTrace();
                return;
            }
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                OptimizationFrame mf = new OptimizationFrame();
                OptimizationFrame.optFrameInstance = mf;
                mf.setVisible(true);
//                Dbg.toAppend = mf.getMessagesTextArea();
            }
        });
    }

    public static OptimizationFrame getOptFrameInstance() {
        return optFrameInstance;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField evalRepetitionsjTextField1;
    private javax.swing.JPanel fitnessjPanel5;
    private javax.swing.JTextField iterationsjTextField2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JPanel killsByBotTypejPanel5;
    private javax.swing.JPanel killsChartjPanel5;
    private javax.swing.JPanel killsPerDeathjPanel6;
    private javax.swing.JTextField maxIterScorejTextField1;
    private javax.swing.JButton refreshResultsChartsjButton4;
    private javax.swing.JTextArea resultDetailsTextArea1;
    private javax.swing.JList resultsjList1;
    private javax.swing.JButton runjButton1;
    private javax.swing.JPanel textjPanel4;
    private javax.swing.JTextField timescalejTextField1;
    // End of variables declaration//GEN-END:variables
}
